"""Loaders for the canonical topology and the visual layouts.

Ported from node-api/src/map/topology.js. shared/network.json is generated by
ttcmap.gtfs.network; shared/layouts/<name>.json is one file per visual design.
"""

import json
import re
from functools import lru_cache
from pathlib import Path

from ttcmap.config import get_settings

# layout and led-map names arrive from the query string, so they are matched
# against this before being used to build a path
SAFE_NAME = re.compile(r"^[a-z][a-z0-9-]*$")


@lru_cache(maxsize=1)
def load_topology() -> dict:
    path = get_settings().shared_path / "network.json"
    if not path.exists():
        raise FileNotFoundError(
            f"Topology not found at {path}. Run a GTFS refresh to generate it."
        )
    return json.loads(path.read_text())


def clear_cache() -> None:
    """Called after a GTFS refresh regenerates network.json."""
    load_topology.cache_clear()


def safe_json_path(directory: Path, name: str, kind: str) -> Path:
    if not SAFE_NAME.match(name):
        raise ValueError(f"Invalid {kind} name: {name}")
    return directory / f"{name}.json"


def load_layout(name: str) -> dict | None:
    path = safe_json_path(get_settings().shared_path / "layouts", name, "layout")
    if not path.exists():
        return None
    return json.loads(path.read_text())


def station_order(topology: dict, line_id: str, direction: int) -> list[str]:
    """Stations of a line in travel order (network.json lists direction 0 order)."""
    line = next((line for line in topology["lines"] if line["id"] == line_id), None)
    if not line:
        return []
    return line["stations"] if direction == 0 else list(reversed(line["stations"]))


def previous_station(topology: dict, line_id: str, direction: int, station_id: str) -> str | None:
    """The station a train came from, given the station it is approaching."""
    order = station_order(topology, line_id, direction)
    try:
        index = order.index(station_id)
    except ValueError:
        return None
    return order[index - 1] if index > 0 else None
