#!/bin/bash
set -e

# ─────────────────────────────────────────────
# TTC-Map — Full Environment Setup (macOS/Linux/WSL/Git-Bash)
# Run:
#   bash setup/setup.sh
# ─────────────────────────────────────────────

# Project root = parent of this script's directory
PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
echo "📂 Project root: $PROJECT_ROOT"

REQ_FILE="$PROJECT_ROOT/requirements.txt"
VENV_DIR="$PROJECT_ROOT/venv"
VENV_PY="$VENV_DIR/bin/python"
API_DIR="$PROJECT_ROOT/API"

# ── 1. Fix requirements.txt encoding (UTF-16 → UTF-8) ──
echo ""
echo "🔧 Fixing requirements.txt encoding..."

if [ -f "$REQ_FILE" ]; then
  if file "$REQ_FILE" | grep -qi "utf-16\|bom"; then
    iconv -f UTF-16 -t UTF-8 "$REQ_FILE" \
      | sed 's/\r//g' | grep -v '^\s*$' > "$PROJECT_ROOT/requirements_fixed.txt"
    mv "$PROJECT_ROOT/requirements_fixed.txt" "$REQ_FILE"
    echo "   ✅ Converted to UTF-8"
  else
    # Still normalize CRLF and remove empty lines, keep as UTF-8
    sed 's/\r//g' "$REQ_FILE" | grep -v '^\s*$' > "$PROJECT_ROOT/requirements_fixed.txt"
    mv "$PROJECT_ROOT/requirements_fixed.txt" "$REQ_FILE"
    echo "   ✅ Already UTF-8 (normalized line endings)"
  fi
else
  echo "   ⚠ requirements.txt not found (will be generated by pipreqs)"
fi

# ── 2. Python virtual environment ──
echo ""
echo "🐍 Setting up Python virtual environment..."

if [ ! -d "$VENV_DIR" ]; then
  python3 -m venv "$VENV_DIR"
  echo "   ✅ venv created"
else
  echo "   ✅ venv already exists"
fi

echo "📦 Upgrading pip and installing pipreqs..."
"$VENV_PY" -m pip install --upgrade pip
"$VENV_PY" -m pip install pipreqs

echo "🔍 Scanning Python files for imports with pipreqs..."
"$VENV_PY" -m pipreqs "$API_DIR" --force --savepath "$REQ_FILE"
if grep -q "^fastapi$" "$REQ_FILE"; then
  sed -i.bak 's/^fastapi$/fastapi[standard]/' "$REQ_FILE"
  rm -f "$REQ_FILE.bak"
fi
echo "   ✅ requirements.txt updated from source scan:"
cat "$REQ_FILE"

echo ""
echo "📦 Installing Python dependencies..."
"$VENV_PY" -m pip install -r "$REQ_FILE"
echo "   ✅ Python packages installed"

# ── 3. Node.js dependencies ──
echo ""
echo "📦 Installing Node.js dependencies..."
cd "$PROJECT_ROOT/node-api"
npm ci
echo "   ✅ Node packages installed"

# ── 4. Summary ──
echo ""
echo "═══════════════════════════════════════════"
echo "  ✅  Setup complete!"
echo "═══════════════════════════════════════════"
echo ""
echo "  PYTHON API (FastAPI):"
echo "    Activate venv:   source venv/bin/activate"
echo "    Init DB:         cd API/src && python update_db.py"
echo "    Run server:      fastapi dev API/src/main.py"
echo ""
echo "  NODE API (Express):"
echo "    Start server:    cd node-api && npm start"
echo "    Dev mode:        cd node-api && npm run dev"
echo "    Frontend:        http://localhost:3000"
echo ""
echo "═══════════════════════════════════════════"
